name: Sanity cart tests
on: push
jobs:
  cart-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         browser: chrome
         command: npm run test:cart

      - name: Cypress Test Cart Report
        uses: actions/upload-artifact@v4
        with:
          name: cartTest Report
          path: cypress/reports/html 


  register-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         browser: chrome
         command: npm run test:registerFlow

      - name: Cypress Test Register Report
        uses: actions/upload-artifact@v4
        with:
          name: RegisterFlow Report
          path: cypress/reports/html